"""add output_index

Revision ID: 29786148c766
Revises: b7c960ee7f28
Create Date: 2026-02-28 00:42:20.255454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29786148c766'
down_revision: Union[str, Sequence[str], None] = 'b7c960ee7f28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('execution_node', sa.Column('output_index', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('execution_node', 'output_index')
    # ### end Alembic commands ###
