"""Add ondelete CASCADE to ExecutionNode

Revision ID: 7e2037e10b22
Revises: 6c7bf4981965
Create Date: 2026-03-01 19:26:50.068192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e2037e10b22'
down_revision: Union[str, Sequence[str], None] = '6c7bf4981965'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('execution_node_execution_id_fkey'), 'execution_node', type_='foreignkey')
    op.create_foreign_key(None, 'execution_node', 'execution', ['execution_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'execution_node', type_='foreignkey')
    op.create_foreign_key(op.f('execution_node_execution_id_fkey'), 'execution_node', 'execution', ['execution_id'], ['id'])
    # ### end Alembic commands ###
