"""add execution and execution_node tables

Revision ID: b7c960ee7f28
Revises: 1309f2c716b6
Create Date: 2026-02-27 22:19:06.467793

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b7c960ee7f28"
down_revision: Union[str, Sequence[str], None] = "1309f2c716b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "execution",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workflow_id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "RUNNING", "COMPLETED", "FAILED", name="executionstatus"
            ),
            nullable=False,
        ),
        sa.Column(
            "state",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["workflow.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_execution_owner_id"), "execution", ["owner_id"], unique=False
    )
    op.create_index(
        op.f("ix_execution_workflow_id"), "execution", ["workflow_id"], unique=False
    )
    op.create_table(
        "execution_node",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("execution_id", sa.Uuid(), nullable=False),
        sa.Column("node_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "SUCCESS",
                "ERROR",
                "SKIPPED",
                name="nodeexecutionstatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "input_data",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column(
            "output_data",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["execution_id"],
            ["execution.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_execution_node_execution_id"),
        "execution_node",
        ["execution_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_execution_node_node_id"), "execution_node", ["node_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_execution_node_node_id"), table_name="execution_node")
    op.drop_index(op.f("ix_execution_node_execution_id"), table_name="execution_node")
    op.drop_table("execution_node")
    op.drop_index(op.f("ix_execution_workflow_id"), table_name="execution")
    op.drop_index(op.f("ix_execution_owner_id"), table_name="execution")
    op.drop_table("execution")
    # ### end Alembic commands ###
